apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv
  namespace: media
spec:
  capacity:
    storage: 600Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/jellyfin
    server: 10.0.0.15