apiVersion: v1
kind: List
items:
  - apiVersion: cilium.io/v2
    kind: CiliumNetworkPolicy
    metadata:
      name: allow-ingress-nginx-to-jellyfin
      namespace: media
    spec:
      endpointSelector:
        matchLabels:
          app: jellyfin
      ingress:
      - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: ingress-nginx
        toPorts:
        - ports:
          - port: "80"
            protocol: TCP
          - port: "8096"
            protocol: TCP

  - apiVersion: cilium.io/v2
    kind: CiliumNetworkPolicy
    metadata:
      name: allow-flux-system-to-jellyfin
      namespace: media
    spec:
      endpointSelector:
        matchLabels:
          app: jellyfin
      ingress:
      - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: flux-system
        toPorts:
        - ports:
          - port: "80"
            protocol: TCP
          - port: "443"
            protocol: TCP

  - apiVersion: cilium.io/v2
    kind: CiliumNetworkPolicy
    metadata:
      name: allow-jellyfin-to-coredns
      namespace: media
    spec:
      endpointSelector:
        matchLabels:
          app: jellyfin
      egress:
        - toEndpoints:
          - matchLabels:
              k8s:io.kubernetes.pod.namespace: kube-system
              k8s-app: coredns
          toPorts:
            - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
  
  - apiVersion: cilium.io/v2
    kind: CiliumNetworkPolicy
    metadata:
      name: allow-jellyfin-to-fqdns
      namespace: media
    spec:
      endpointSelector:
        matchLabels:
          app: jellyfin
      egress:
        - toFQDNs:
            - matchName: "api.themoviedb.org"
            - matchName: "api.tmdb.org"
            - matchName: "www.omdbapi.com"
          toPorts:
            - ports:
                - port: "443"
                  protocol: TCP