apiVersion: v1
kind: List
items: 
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-ingress-nginx-to-jellyfin
      namespace: media
    spec:
      podSelector:
        matchLabels:
          app: jellyfin
      policyTypes:
      - Ingress
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8096
        - protocol: TCP
          port: 8920
        - protocol: UDP
          port: 1900
        - protocol: UDP
          port: 7359
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-flux-system-to-jellyfin
      namespace: media
    spec:
      podSelector: {}
      policyTypes:
      - Ingress
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: flux-system
        ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-jellyfin-to-ingress-nginx
      namespace: media
    spec:
      podSelector:
        matchLabels:
          app: jellyfin
      policyTypes:
      - Egress
      egress:
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector: {}
        ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8096
        - protocol: TCP
          port: 8920
        - protocol: UDP
          port: 1900
        - protocol: UDP
          port: 7359
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-jellyfin-to-coredns
      namespace: media
    spec:
      podSelector:
        matchLabels:
          app: jellyfin
      policyTypes:
      - Egress
      egress:
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: coredns
        ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53