apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
spec:
  template:
    spec:
      initContainers:
      - name: install-cni
        image: ghcr.io/siderolabs/install-cni:v1.10.0-alpha.0-2-gf4a110f  # adapt this version to your Talos version if needed
        command:
          - /install-cni.sh
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
          mountPropagation: Bidirectional
