apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-pvc
  namespace: obsidian
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi