apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-newt-tunnel-to-ingress-nginx
  namespace: newt
spec:
  podSelector:
    matchLabels:
      app: newt-tunnel
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443