apiVersion: v1
kind: List
items:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-newt-tunnel-to-ingress-nginx
      namespace: ingress-nginx
    spec:
      podSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
      policyTypes:
      - Ingress
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: newt
        ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-flux-to-nginx-webhook
      namespace: ingress-nginx
    spec:
      podSelector: {}
      policyTypes:
      - Ingress
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: flux-system
        ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-ingress-nginx-to-jellyfin
      namespace: ingress-nginx
    spec:
      podSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
      policyTypes:
      - Egress
      egress:
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: media
        ports:
        - protocol: TCP
          port: 80
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: coredns
        ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53