apiVersion: v1
kind: List
items:
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-newt-tunnel-to-ingress-nginx
      namespace: ingress-nginx
    spec:
      podSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
      policyTypes:
      - Ingress
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: newt
        ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-flux-to-nginx-webhook
      namespace: ingress-nginx
    spec:
      podSelector: {}
      policyTypes:
      - Ingress
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: flux-system
        ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-ingress-nginx-to-jellyfin
      namespace: ingress-nginx
    spec:
      podSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
      policyTypes:
      - Egress
      egress:
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: media
        ports:
        - protocol: TCP
          port: 80
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-ingress-nginx-to-coredns
      namespace: ingress-nginx
    spec:
      podSelector:
        matchLabels:
          kubernetes.io/name: ingress-nginx
      policyTypes:
      - Egress
      egress:
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: coredns
        ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-egress-to-nginx-webhook
      namespace: ingress-nginx
    spec:
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
      policyTypes:
      - Egress
      egress:
      - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/component: controller
        ports:
        - protocol: TCP
          port: 443
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-admission-job-egress
      namespace: ingress-nginx
    spec:
      podSelector:
        matchLabels:
          job-name: ingress-nginx-admission-create
      policyTypes:
      - Egress
      egress:
      - to:
        - ipBlock:
            cidr: 10.96.0.1/32
        ports:
        - protocol: TCP
          port: 443