apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wikijs
  namespace: wikijs
spec:
  interval: 10m0s
  chart:
    spec:
      chart: wiki
      version: ">=3.7.0"
      sourceRef:
        kind: HelmRepository
        name: wikijs
        namespace: wikijs
      interval: 10m0s
  targetNamespace: wikijs
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: wikijs-secret
      valuesKey: values.yaml
