apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wikijs
  namespace: wikijs
spec:
  interval: 10m0s
  chart:
    spec:
      chart: wiki
      sourceRef:
        kind: HelmRepository
        name: wikijs
        namespace: wikijs
      interval: 10m0s
  targetNamespace: wikijs
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    postgresql:
      enabled: false
      postgresqlHost: 10.0.0.15
      postgresqlPort: 5432
      postgresqlUser: wikijs
      postgresqlDatabase: wikijs
      existingSecret: wikijs-wikijs
    persistence:
      enabled: true
      existingClaim: wikijs-pvc
