name: Terraform CI

on:
  pull_request:
    paths:
      - 'infra/**/*.tf'

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.0'

      - name: Terraform Format & Validate
        run: terraform fmt -check && terraform validate